<?php
declare(strict_types=1);

namespace Nivc\Services;

use Nivc\Core\Db;
use Nivc\Core\NowTime;

/** Page-view collection. Cookie-less: the visitor id is generated by the tracker and only its salted hash is stored. */
final class TrackingService
{
    private const VISIT_WINDOW_MIN = 30;

    /** @return array{counted:bool,reason?:string} */
    public static function record(array $site, array $in, string $ua, string $ip): array
    {
        if ($ua === '' || preg_match('/bot|crawl|spider|slurp|preview|headless|lighthouse|monitor|uptime|curl|wget|python|facebookexternalhit/i', $ua)) {
            return ['counted' => false, 'reason' => 'bot'];
        }
        $path = (string) ($in['path'] ?? '');
        $key  = Domain::normalizePath($path === '' ? '/' : mb_substr($path, 0, 400));
        $lpId = Db::val(
            "SELECT id FROM landing_pages WHERE website_id = ? AND path_key = ? AND status = 'active' ORDER BY id LIMIT 1",
            [$site['id'], $key]
        );
        if (!$lpId) {
            return ['counted' => false, 'reason' => 'unknown_page'];
        }
        $vid = (string) ($in['vid'] ?? '');
        if (!preg_match('/^[A-Za-z0-9_-]{8,64}$/', $vid)) {
            return ['counted' => false, 'reason' => 'bad_visitor'];
        }
        $hash = substr(hash_hmac('sha256', $site['site_key'] . '|' . $vid, (string) \Nivc\Core\Config::get('app_key')), 0, 32);
        $day  = NowTime::today();
        $now  = NowTime::mysql();
        $utmS = mb_substr(trim((string) ($in['utm_source'] ?? '')), 0, 190);
        $utmM = mb_substr(trim((string) ($in['utm_medium'] ?? '')), 0, 190);
        $utmC = mb_substr(trim((string) ($in['utm_campaign'] ?? '')), 0, 190);
        $ref  = mb_substr(trim((string) ($in['referrer'] ?? '')), 0, 500);
        $source = Domain::classifySource($utmS, $utmM, $ref);
        $device = Domain::deviceFromUa($ua);
        $threshold = date('Y-m-d H:i:s', strtotime($now) - self::VISIT_WINDOW_MIN * 60);

        $existing = Db::one('SELECT views, last_seen FROM page_views WHERE landing_page_id = ? AND day = ? AND visitor_hash = ?', [$lpId, $day, $hash]);
        if (!$existing) {
            Db::exec(
                'INSERT INTO page_views (landing_page_id, day, visitor_hash, client_id, website_id, views, source, utm_source, utm_campaign, device, first_seen, last_seen)
                 VALUES (?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE last_seen = VALUES(last_seen)',
                [$lpId, $day, $hash, $site['client_id'], $site['id'], $source, $utmS, $utmC, $device, $now, $now]
            );
            return ['counted' => true];
        }
        // Same visitor, same page, same day: a refresh within the visit window is not a new visit.
        if ($existing['last_seen'] < $threshold) {
            Db::exec('UPDATE page_views SET views = views + 1, last_seen = ? WHERE landing_page_id = ? AND day = ? AND visitor_hash = ?', [$now, $lpId, $day, $hash]);
            return ['counted' => true];
        }
        Db::exec('UPDATE page_views SET last_seen = ? WHERE landing_page_id = ? AND day = ? AND visitor_hash = ?', [$now, $lpId, $day, $hash]);
        return ['counted' => false, 'reason' => 'refresh'];
    }
}
