<?php
// Normally generated by the web installer (/install). Copy to config.php only for manual setups.
return [
    'env'            => 'production',            // 'local' logs password-reset links and shows error details
    'timezone'       => 'Asia/Jerusalem',
    'default_locale' => 'he',                     // 'he' or 'en'
    'app_key'        => 'BASE64_32_RANDOM_BYTES', // php -r "echo base64_encode(random_bytes(32));"
    'base_url'       => '',                       // optional, e.g. https://nivcreative.com/panel
    'ip_header'      => null,                     // e.g. 'HTTP_CF_CONNECTING_IP' behind a trusted proxy/CDN
    'mail_from'      => 'no-reply@nivcreative.com',
    'support_email'  => 'support@nivcreative.com',
    'db'             => ['host' => 'localhost', 'port' => 3306, 'name' => '', 'user' => '', 'pass' => '', 'charset' => 'utf8mb4'],
];
