#!/usr/bin/env python3
"""Generates lang/he.php and lang/en.php from tools/i18n_table.py and checks that every key used in code exists."""
import re, sys, os
sys.path.insert(0, os.path.dirname(__file__))
from i18n_table import T
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
keys = [k for k, _, _ in T]
dups = {k for k in keys if keys.count(k) > 1}
if dups: sys.exit('duplicate keys: %s' % sorted(dups))
def esc(s): return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"
for idx, loc in ((1, 'he'), (2, 'en')):
    lines = ["<?php", "// GENERATED by tools/build_lang.py from tools/i18n_table.py — edit the table, not this file.", "return ["]
    for row in T:
        lines.append("    %s => %s," % (esc(row[0]), esc(row[idx])))
    lines.append("];")
    open(os.path.join(root, 'lang', loc + '.php'), 'w', encoding='utf8').write("\n".join(lines) + "\n")
# verify static keys used in code
used = set()
for base, _, files in os.walk(root):
    if any(p in base for p in ('/tests', '/tools', '/storage', '/.git')): continue
    for f in files:
        if f.endswith(('.php', '.js')):
            src = open(os.path.join(base, f), encoding='utf8').read()
            used |= set(re.findall(r"(?<![A-Za-z0-9_])(?:NC\.)?t\('([a-z_]+\.[A-Za-z0-9_.]+)'", src))
missing = sorted(k for k in used if k not in keys and not k.endswith('.'))
print('keys: %d, used static: %d, missing: %d' % (len(keys), len(used), len(missing)))
for m in missing: print('  MISSING', m)
sys.exit(1 if missing else 0)
