<?php
declare(strict_types=1);

namespace Nivc\Controllers\Web;

use Nivc\Core\Auth;
use Nivc\Core\Config;
use Nivc\Core\Db;
use Nivc\Core\I18n;
use Nivc\Core\NowTime;
use Nivc\Core\Request;
use Nivc\Core\Response;
use Nivc\Core\View;

/**
 * One-time web installer. Writes config/config.php, creates the schema and the first administrator,
 * then locks itself with storage/installed.lock. Remove /install afterwards if you like.
 */
final class InstallController
{
    public static function handle(Request $r): Response
    {
        I18n::setLocale('he');
        $errors = [];
        $vals = ['db_host' => 'localhost', 'db_port' => '3306', 'db_name' => '', 'db_user' => '', 'admin_name' => '', 'admin_email' => '', 'site_url' => ''];
        if ($r->method === 'POST') {
            foreach ($vals as $k => $_) {
                $vals[$k] = trim((string) ($r->post[$k] ?? ''));
            }
            $pass = (string) ($r->post['db_pass'] ?? '');
            $admPass = (string) ($r->post['admin_pass'] ?? '');
            if (!filter_var($vals['admin_email'], FILTER_VALIDATE_EMAIL)) {
                $errors['admin_email'] = t('validation.email');
            }
            if ($vals['admin_name'] === '') {
                $errors['admin_name'] = t('validation.required');
            }
            if (!Auth::validPasswordRule($admPass)) {
                $errors['admin_pass'] = t('validation.password_rule');
            }
            if (!$errors) {
                try {
                    $db = ['host' => $vals['db_host'], 'port' => (int) $vals['db_port'], 'name' => $vals['db_name'], 'user' => $vals['db_user'], 'pass' => $pass, 'charset' => 'utf8mb4'];
                    Db::reset();
                    $pdo = Db::connect($db);
                    $pdo->exec("SET time_zone = '+00:00'");
                    self::runSchema($pdo);
                    $key = base64_encode(random_bytes(32));
                    Config::set(['db' => $db, 'app_key' => $key]);
                    $now = (new \DateTimeImmutable('now', new \DateTimeZone('Asia/Jerusalem')))->format('Y-m-d H:i:s');
                    if (!Db::val("SELECT id FROM users WHERE role = 'admin' LIMIT 1")) {
                        Db::insert('users', ['client_id' => null, 'role' => 'admin', 'email' => mb_strtolower($vals['admin_email']), 'password_hash' => Auth::hashPassword($admPass),
                            'name' => $vals['admin_name'], 'locale' => 'he', 'status' => 'active', 'created_at' => $now, 'updated_at' => $now]);
                    }
                    $cfg = [
                        'env' => 'production', 'timezone' => 'Asia/Jerusalem', 'default_locale' => 'he', 'app_key' => $key,
                        'base_url' => rtrim($vals['site_url'], '/'), 'db' => $db,
                    ];
                    $php = "<?php\n// Generated by the NivCreative Panel installer. Keep this file private.\nreturn " . var_export($cfg, true) . ";\n";
                    if (@file_put_contents(Config::root() . '/config/config.php', $php, LOCK_EX) === false) {
                        throw new \RuntimeException('config/config.php is not writable');
                    }
                    @chmod(Config::root() . '/config/config.php', 0640);
                    file_put_contents(Config::root() . '/storage/installed.lock', date('c'));
                    return Response::redirect(url('/login'));
                } catch (\Throwable $e) {
                    $errors['general'] = $e->getMessage();
                }
            }
        }
        return Response::html(View::render('layouts/auth', [
            'view' => 'install/form', 'title' => t('install.title'), 'csrf' => '', 'errors' => $errors, 'vals' => $vals,
            'supportEmail' => '', 'supportWa' => '', 'install' => true,
        ]));
    }

    public static function runSchema(\PDO $pdo): void
    {
        $sql = (string) file_get_contents(Config::root() . '/database/schema.sql');
        foreach (array_filter(array_map('trim', preg_split('/;\s*\n/', $sql) ?: [])) as $stmt) {
            if (!preg_match('/^(--.*\n)*\s*$/', $stmt)) {
                $pdo->exec(Db::prefixSql($stmt));
            }
        }
    }
}
